winget install -e --id Notepad++.Notepad++
winget install -e --id OpenJS.NodeJS
winget install -e --id ArduinoSA.IDE.beta
winget install -e --id Git.Git
winget install -e --id GitHub.cli
winget install -e --id GitHub.GitHubDesktop
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Valve.Steam
winget install -e --id Docker.DockerDesktop
winget install -e --id Discord.Discord
winget install -e --id Python.Python.3
winget install -e --id Audacity.Audacity
winget install -r --id Flow-Launcher.Flow-Launcher
winget install -e --id FedericoTerzi.espanso
winget install -e --id Google.Chrome
winget install -e --id 7zip.7zip
winget install -e --id VideoLAN.VLC
winget install -e --id Notion.Notion
winget install -e --id Oracle.JDK.17
winget install -e --id KiCad.KiCad
winget install -e --id HTTPie.HTTPie
winget install -e --id UderzoSoftware.SpaceSniffer
winget install -e --id Mozilla.Firefox
winget install -e --id Telegram.TelegramDesktop
winget install -e --id Spotify.Spotify
winget install -e --id Mojang.MinecraftLauncher
winget install -e --id Bitwarden.Bitwarden
winget install -e --id OBSProject.OBSStudio
winget install -e --id GIMP.GIMP
winget install -e --id NordVPN.NordVPN
winget install -e --id qBittorrent.qBittorrent
winget install -e --id YTmdesktop.Ytmdesktop
winget install -e --id Nvidia.GeForceExperience
winget install -e --id EpicGames.EpicGamesLauncher
winget install -e --id Project64.Project64
winget install -e --id Libretro.RetroArch
winget install -e --id PuTTY.PuTTY
winget install -e --id voidtools.Everything
winget install -e --id Parsec.Parsec
winget install -e --id Postman.Postman
winget install -e --id RaspberryPiFoundation.RaspberryPiImager
winget install -e --id Ultimaker.Cura
winget install -e --id Microsoft.PowerToys
winget install -e --id TimKosse.FileZilla.Client
winget install -e --id WinSCP.WinSCP
winget install -e --id WireGuard.WireGuard
winget install -e --id UnityTechnologies.UnityHub
winget install -e --id Microsoft.VisualStudio.2022.Community-Preview
